version: "2"
services:
  # node:
  #   image: "node:latest"
  #   user: "node"
  #   working_dir: /home/node/app
  #   environment:
  #     - NODE_ENV=development
  #   volumes:
  #     - ./:/home/node/app
  #   ports:
  #     - "3000:3000"
  #   command: "npm start"
  mariadb:
    image: mariadb:10.4
    container_name: mariadb
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=rootpsss
      - MYSQL_DATABASE=severino
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    ports:
      - "3306:3306"